### ISSUE TITLE
Create CDM, LDM, PDM

### ISSUE THREAD

**Issue by elizaveta-titova** [elizaveta-titova/ADM-Project-Restaurant-food-delivery#1]
Colleagues, here's the link to edit the conceptual, logical and physical diagrams: https://app.diagrams.net/#Helizaveta-titova%2FADM-Project-Restaurant-food-delivery%2Fmain%2FCDM%20(Food%20ordering)%20.drawio

**Comment by elizaveta-titova** [comment]
That is the first version of CDM.
![image](https://github.com/elizaveta-titova/ADM-Project-Restaurant-food-delivery/assets/133528364/fcdfe73f-d570-44d8-9543-a1308d5e9c44)

**Comment by fuljencia** [comment]
@elizaveta-titova , I have some suggestions for the CDM, pls, take a look at the latest commit
I think we should add more entities

**Comment by elizaveta-titova** [comment]
@fuljencia Yes, I agree with you. Now, I've added some new entities to make the proccess more complex. Also, I've tried to use Visual Paradigm tools to build CDM, LDM.
This is LDM (which is built in UML notation)
![image](https://github.com/elizaveta-titova/ADM-Project-Restaurant-food-delivery/assets/133528364/e497886f-766d-4ad3-b043-c43b8dcc4b82)

**Comment by elizaveta-titova** [comment]
This is CDM 
![image](https://github.com/elizaveta-titova/ADM-Project-Restaurant-food-delivery/assets/133528364/c52d75a3-d886-4f75-85a8-037a1ebc488a)

**Comment by elizaveta-titova** [comment]
This is PDM
![image](https://github.com/elizaveta-titova/ADM-Project-Restaurant-food-delivery/assets/133528364/fb8eb00c-2564-4428-a854-e86b1df3a69d)

**Comment by elizaveta-titova** [comment]
Collegues, please, if you have any comments or suggestions write below and we'll discuss it.

**Comment by fuljencia** [comment]
@elizaveta-titova, cool! As we discussed during our zoom-call, the connection between the Person and the Client, Courier and Administrator is inheritance.  As far as I see on the CDM, we should change the direction of the lines and make it from the heirs to the more abstract class - Person.

**Comment by fuljencia** [comment]
@elizaveta-titova , be the way, it's "illegal" to name the table as plurals, pls, change the name of the table Order Items

**Comment by elizaveta-titova** [comment]
@fuljencia thank you for your comments. I tried to take into account all the comments and made the necessary adjustments to the diagrams. So, here's the final result of the diagrams. Please, if you agree with the final version, write below or suggest your corrections.
**CDM**
![CDM](https://github.com/elizaveta-titova/ADM-Project-Restaurant-food-delivery/assets/133528364/7fa6aa6c-3bdc-4105-aa1f-4403f3470b7f)
**LDM**
![LDM](https://github.com/elizaveta-titova/ADM-Project-Restaurant-food-delivery/assets/133528364/db01ab42-fc8d-4c45-a3c7-deb762ac1bc8)
**PDM**
![PDM](https://github.com/elizaveta-titova/ADM-Project-Restaurant-food-delivery/assets/133528364/084aa9bc-869b-4172-a7d8-cc7fb4a28798)

**Comment by elizaveta-titova** [comment]
I removed watermarks from images.
**CDM**
![CDM](https://github.com/elizaveta-titova/ADM-Project-Restaurant-food-delivery/assets/133528364/6a7ea807-e7f3-4d3c-862c-4a1693bfba94)
**LDM
![LDM](https://github.com/elizaveta-titova/ADM-Project-Restaurant-food-delivery/assets/133528364/9eabcbd5-4cd7-450e-b723-7bcf1e671758)
PDM**
![PDM](https://github.com/elizaveta-titova/ADM-Project-Restaurant-food-delivery/assets/133528364/6f57d072-45dd-4217-8e1c-9ce4b56a52e4)

**Comment by fuljencia** [comment]
@elizaveta-titova , now the diagrams look great! I think you've done a great job, thank you for this!
