### ISSUE TITLE
Create UML diagrams (use-case)

### ISSUE THREAD

**Issue by elizaveta-titova** [elizaveta-titova/ADM-Project-Restaurant-food-delivery#2]
Based on the provided business-case, build use-case diagram for the process of food delivery.

**Comment by fuljencia** [comment]
Colleagues, here's the first version of the Use-case diagram for our business-case. For now, I suggest to concentrate on the three cases, that I temporarily marked green. Pls, leave your comments about the diagram below.
The link to edit the diagram: https://drive.google.com/file/d/18F0onXpJFFFDFOeIohF1fbg8kFEM1Rwg/view?usp=sharing
The image: 
![image](https://github.com/elizaveta-titova/ADM-Project-Restaurant-food-delivery/assets/44914881/4c07c4c7-70c7-464f-ad15-f496f31e3d9f)

**Comment by elizaveta-titova** [comment]
The diagram is great, all aspects are mentioned. Yes, I agree with you to concentrate mostly on these three stages.

**Comment by fuljencia** [comment]
Good! I think I will close this issue and move on to the issue with activity diagrams!
