### ISSUE TITLE
Create UML diagrams (activity)

### ISSUE THREAD

**Issue by elizaveta-titova** [elizaveta-titova/ADM-Project-Restaurant-food-delivery#3]

**Comment by fuljencia** [comment]
Colleagues, I have built some UML activity diagrams. Pls, check the link below and leave your comments: https://app.diagrams.net/#Helizaveta-titova%2FADM-Project-Restaurant-food-delivery%2Fmain%2FUML.drawio.xml

**Comment by elizaveta-titova** [comment]
@fuljencia I corrected a few minor moments. I think that the diagrams are correct and included everything needed. Thank you!

**Comment by fuljencia** [comment]
@elizaveta-titova , great! thank you for your help!
