### ISSUE TITLE
Master Data

### ISSUE THREAD

**Issue by elizaveta-titova** [elizaveta-titova/ADM-Project-Restaurant-food-delivery#6]

**Comment by elizaveta-titova** [comment]
Stage 1
The quality of each data source was assessed. Some of the columns had missing and invalid values.
![image](https://github.com/elizaveta-titova/ADM-Project-Restaurant-food-delivery/assets/133528364/dd75fb32-4fd8-40c9-8c04-b752b1765ec8)

**Comment by elizaveta-titova** [comment]
Moreover, the case of some columns was different, so this columns were ticked and standardized.
![image](https://github.com/elizaveta-titova/ADM-Project-Restaurant-food-delivery/assets/133528364/ec804404-e787-40e7-b540-58dc211a715e)
The phone numbers included some characters and it was difficult to compare them, so these unnecessary characters were removed.
![image](https://github.com/elizaveta-titova/ADM-Project-Restaurant-food-delivery/assets/133528364/ce108c46-2572-459d-be0b-708f20afea7e)

**Comment by elizaveta-titova** [comment]
Also definitions were set, according to which the data will be compared in the future.
![image](https://github.com/elizaveta-titova/ADM-Project-Restaurant-food-delivery/assets/133528364/3d0e4fdc-8cc9-4c03-92b3-8af3728ae756)
![image](https://github.com/elizaveta-titova/ADM-Project-Restaurant-food-delivery/assets/133528364/27e481e7-1001-4dc3-947e-cf325b6fa98b)
![image](https://github.com/elizaveta-titova/ADM-Project-Restaurant-food-delivery/assets/133528364/549ae943-5afa-41bd-80c9-b4f9eb85bd64)

**Comment by elizaveta-titova** [comment]
Merge & Survivorship
At this stage, the setting was made to overwrite the records so that in the final export the data about owners would be the most complete and contain all phone numbers and emails.
![image](https://github.com/elizaveta-titova/ADM-Project-Restaurant-food-delivery/assets/133528364/56de177e-371a-47b8-a97d-15dc39c62e88)

**Comment by elizaveta-titova** [comment]
That is the final export that shows a master record. It is the one single source of truth that has all the emails, phone numbers and correct addresses.
![image](https://github.com/elizaveta-titova/ADM-Project-Restaurant-food-delivery/assets/133528364/afdfc888-3bf9-49bf-8f0c-64dcc5db4aa3)

**Comment by alenkaseledka** [comment]
Liza, it's a nice job!
