### ISSUE TITLE
Create presentation (readme) file

### ISSUE THREAD

**Issue by elizaveta-titova** [elizaveta-titova/ADM-Project-Restaurant-food-delivery#7]

**Comment by fuljencia** [comment]
Guys, I suggest to use our readme.markdown file for the presentation

**Comment by elizaveta-titova** [comment]
@fuljencia yes, that's good idea. Let's add some pictures of the stages and description for them.

**Comment by elizaveta-titova** [comment]
@fuljencia yes, that's good idea. Let's add some pictures of the stages and description for them.
