### ISSUE TITLE
Data warehouse architecture 

### ISSUE THREAD

**Issue by fuljencia** [elizaveta-titova/ADM-Project-Restaurant-food-delivery#8]

**Comment by elizaveta-titova** [comment]
I've created an overall scheme of Data Warehouse for our process.
![DWH scheme](https://github.com/elizaveta-titova/ADM-Project-Restaurant-food-delivery/assets/133528364/989f8ba3-9934-4189-829f-e0d90173fc63)

**Comment by elizaveta-titova** [comment]
Here's the conceptual diagram for Data Warehouse Architecture built in Visual Paradigm.
![image](https://github.com/elizaveta-titova/ADM-Project-Restaurant-food-delivery/assets/133528364/ee2799e4-fdf1-4424-b482-e97008ea4d99)

**Comment by elizaveta-titova** [comment]
There are more attributes for some of the entities as we decided to widen our process. I thought it'll be interesting to find such data, to work with it and build graphs in BI.
According to this CD we can build Data Warehouse in PowerBI.

**Comment by fuljencia** [comment]
Great! We may build interesting reports based on this conceptual model!
