### ISSUE TITLE
Power BI reports

### ISSUE THREAD

**Issue by fuljencia** [elizaveta-titova/ADM-Project-Restaurant-food-delivery#9]

**Comment by fuljencia** [comment]
Guys, I've designed the following [reports](https://github.com/elizaveta-titova/ADM-Project-Restaurant-food-delivery/blob/main/delivery.pdf) in Power BI. Pls, leave your comments below

**Comment by alenkaseledka** [comment]
Alisa, it's wonderful!

**Comment by elizaveta-titova** [comment]
Yes, they are great! I've some suggestions. Maybe, we can add percents or quantities to the first diagram (Orders by Cuisine). And if I'm not mistaken, we should name like this, example: mean rating TO cost of the order. But this is only some details.

**Comment by fuljencia** [comment]
Great! I've made some changes and here's a new [file](https://github.com/elizaveta-titova/ADM-Project-Restaurant-food-delivery/blob/main/delivery-v2.pdf)

**Comment by fuljencia** [comment]
[Here](https://github.com/elizaveta-titova/ADM-Project-Restaurant-food-delivery/blob/main/scheme.png) is the data scheme in Power BI

**Comment by fuljencia** [comment]
I'll also place it in our readme file
